# Site settings
title: Documentation | FLVS Webmaster
email: bradykondek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for the 2022 FLVS TSA Webmaster project
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://documentation.flvswebmaster.ga" # the base hostname & protocol for your site
#twitter_username:
github_username: bradykondek

# Build settings
markdown: kramdown
